stages:
  - build

frontend_build:
  stage: build
  image: node:20
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    name: "frontend-build"
    paths:
      - frontend/dist/
    expire_in: 1 week

backend_build:
  stage: build
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - cd backend
    - mvn clean package
  artifacts:
    name: "backend-build"
    paths:
      - backend/target/*.jar
    expire_in: 1 week
